hangman_api:
    resource: "@HangmanApiBundle/Resources/config/routing.yml"
    prefix:   /api
hangman_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

